- name: Generate kubeadm join command
  shell: kubeadm token create --print-join-command
  register: kubeadm_join_cmd
  delegate_to: "{{ groups['masters'] | first }}"

- name: Run join command
  shell: "{{ kubeadm_join_cmd.stdout }}"
