- name: Kubeadm reset
  shell: kubeadm reset -f

- name: Generate kubeadm join command
  shell: kubeadm token create --print-join-command
  register: kubeadm_join_cmd
  delegate_to: "{{ groups['masters'] | first }}"

- name: Ensure remote config dir exists
  file:
    name: /etc/kubeadm
    state: directory

- name: Generate kubeadm config
  template:
    src: kubeadm.yaml.j2
    dest: /etc/kubeadm/kubeadm.yaml

- name: Run join command
  shell: "{{ kubeadm_join_cmd.stdout }} --config /etc/kubeadm/kubeadm.yaml"
