- name: Copy ipvs modules init file
  copy:
    src: centos/ipvs.modules
    dest: /etc/sysconfig/modules
    mode: '0755'


- name: Enable module ipvs
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
  - ip_vs
  - ip_vs_dh
  - ip_vs_sh
  - ip_vs_rr
  - ip_vs_wrr
