- name: Change sysctl config
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: true
    state: present
    reload: true
  with_items: "{{ sysctl_args }}"

- name: Disable swap
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Copy ipvs modules init file
  copy:
    src: centos/ipvs.modules
    dest: /etc/sysconfig/modules
    mode: '0755'

- name: Enable module ipvs
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
  - ip_vs
  - ip_vs_dh
  - ip_vs_sh
  - ip_vs_rr
  - ip_vs_wrr

- name: Install necessary binary
  yum:
    name:
    - "conntrack"
    - "socat"
    state: present
    update_cache: yes


