- name: Ensure kubelet service exists
  file:
    name: /etc/systemd/system/kubelet.service.d
    state: directory

- name: Copy kubelet service file
  template:
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service

- name: Copy kubeadm conf
  template:
    src: 10-kubeadm.conf.j2
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf

- name: Enable kubelet service
  systemd:
    name: kubelet
    enabled: true
    daemon_reload: true
