- name: Test
  hosts: kubernetes
  tasks:
  - name: test
    debug:
      msg: "{{ ansible_interfaces | map('regex_replace', '-', '_') | map('extract',  ansible_facts) | rejectattr('ipv4', 'undefined') | selectattr('ipv4.address', 'equalto', ansible_ssh_host) | map(attribute='device') | list | first }}"
